blueprint:
  name: Synchronize (1-10) switches with control entity in parallel (symultaniously).
  description: >
    This blueprint synchronizes up to ten switches with the state of a control entity.
    The control entity can be either a switch or an input_boolean.
    It will ensure the switches are turned on or off to match the control entity and will repeat the action until the desired state is achieved for each switch.
    It also will stop if controll entity is swiched to other state.
  domain: automation

  input:
    control_entity:
      name: Control Entity
      description: The switch or input_boolean entity to control the switches.
      selector:
        entity:
          domain:
            - input_boolean
            - switch  # Allow both input_boolean and switch domains

    switch_1:
      name: Switch 1
      description: The first switch entity to be controlled by the control entity.
      selector:
        entity:
          domain: switch

    switch_2:
      name: Switch 2 (Optional)
      description: The second switch entity to be controlled by the control entity.
      selector:
        entity:
          domain: switch
      default:

    delay_time:
      name: Delay Time Between Checks
      description: The amount of time to wait between each check to see if the switches have been set to the correct state.
      default: 1
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
          mode: box

trigger:
  - platform: state
    entity_id: !input control_entity

condition: []

variables:
  switch_1: !input switch_1
  switch_2: !input switch_2

action:
  - parallel:
      - choose:
          - conditions:
              - "{{ not not switch_1 }}"  # Ensure the switch is available
            sequence:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: !input control_entity
                        state: "off"
                    sequence:
                      - repeat:
                          sequence:
                            - service: switch.turn_off
                              target:
                                entity_id: !input switch_1
                            - delay:
                                seconds: !input delay_time
                          until:
                            - condition: or
                              conditions:
                                - condition: state
                                  entity_id: !input switch_1
                                  state: "off"
                                - condition: state
                                  entity_id: !input control_entity
                                  state: "on"
                  - conditions:
                      - condition: state
                        entity_id: !input control_entity
                        state: "on"
                    sequence:
                      - repeat:
                          sequence:
                            - service: switch.turn_on
                              target:
                                entity_id: !input switch_1
                            - delay:
                                seconds: !input delay_time
                          until:
                            - condition: or
                              conditions:
                                - condition: state
                                  entity_id: !input switch_1
                                  state: "on"
                                - condition: state
                                  entity_id: !input control_entity
                                  state: "off"

      - choose:
          - conditions:
              - "{{ switch_2|length > 0 }}"
            sequence:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: !input control_entity
                        state: "off"
                    sequence:
                      - repeat:
                          sequence:
                            - service: switch.turn_off
                              target:
                                entity_id: !input switch_2
                            - delay:
                                seconds: !input delay_time
                          until:
                            - condition: or
                              conditions:
                                - condition: state
                                  entity_id: !input switch_2
                                  state: "off"
                                - condition: state
                                  entity_id: !input control_entity
                                  state: "on"
                  - conditions:
                      - condition: state
                        entity_id: !input control_entity
                        state: "on"
                    sequence:
                      - repeat:
                          sequence:
                            - service: switch.turn_on
                              target:
                                entity_id: !input switch_2
                            - delay:
                                seconds: !input delay_time
                          until:
                            - condition: or
                              conditions:
                                - condition: state
                                  entity_id: !input switch_2
                                  state: "on"
                                - condition: state
                                  entity_id: !input control_entity
                                  state: "off"

mode: parallel
